// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"github.com/google/uuid"
)

type Match struct {
	ID        uuid.UUID
	HomeTeam  string
	AwayTeam  string
	HomeGoals int32
	AwayGoals int32
}
